# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='mockups')),
                ('github_username', models.CharField(max_length=100, unique=True)),
                ('contacts', models.ManyToManyField(to='api.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('slug', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('icon', models.ImageField(null=True, upload_to='icons')),
                ('long_desc', models.TextField(blank=True)),
                ('meta', django_mysql.models.JSONField(default=dict)),
                ('contributors', models.ManyToManyField(to='api.Contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='api.Technology'),
        ),
    ]
