# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-20 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='github_username',
        ),
    ]
