# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_member_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
